apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "keycloak"
            - name: DB_PASSWORD
              value: "keycloak"
          livenessProbe:
            exec:
              command:
                - curl
                - http://localhost:9990/health
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - curl
                - http://localhost:9990/health
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: import-folder
              mountPath: /tmp/resources
      volumes:
        - name: import-folder
          hostPath:
            path: /Users/miguelanciaes/Desktop/multi-tenant-keycloak/keycloak-multi-tenant/k8/resources
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
